export const TEMPLATES = [
  {
    id: 101,
    title: "Scientific Literature Review",
    description:
      "Synthesize existing research on a scientific topic with critical analysis.",
    category: "Research",
    subcategory: "Academic",
    icon: "📚",
    gradient: "from-blue-600 to-cyan-600",
    bgGradient: "from-blue-900/20 to-cyan-900/20",
  },
  {
    id: 102,
    title: "Experimental Research Design",
    description:
      "Create a detailed methodology for experimental research with variables and controls.",
    category: "Research",
    subcategory: "Academic",
    icon: "🧪",
    gradient: "from-violet-600 to-indigo-600",
    bgGradient: "from-violet-900/20 to-indigo-900/20",
  },
  {
    id: 103,
    title: "Quantitative Data Analysis",
    description:
      "Generate statistical analysis of numerical data with meaningful interpretations.",
    category: "Research",
    subcategory: "Academic",
    icon: "📊",
    gradient: "from-emerald-600 to-green-600",
    bgGradient: "from-emerald-900/20 to-green-900/20",
  },
  {
    id: 104,
    title: "Qualitative Research Study",
    description:
      "Design a research approach for gathering and analyzing non-numerical data.",
    category: "Research",
    subcategory: "Academic",
    icon: "🔍",
    gradient: "from-amber-600 to-orange-600",
    bgGradient: "from-amber-900/20 to-orange-900/20",
  },
  {
    id: 105,
    title: "Historical Analysis",
    description:
      "Examine historical events through critical research and primary sources.",
    category: "Research",
    subcategory: "Academic",
    icon: "🏛️",
    gradient: "from-stone-600 to-amber-600",
    bgGradient: "from-stone-900/20 to-amber-900/20",
  },
  {
    id: 106,
    title: "Comparative Case Study",
    description:
      "Compare multiple cases to identify patterns, differences, and insights.",
    category: "Research",
    subcategory: "Academic",
    icon: "⚖️",
    gradient: "from-purple-600 to-fuchsia-600",
    bgGradient: "from-purple-900/20 to-fuchsia-900/20",
  },
  {
    id: 107,
    title: "Meta-Analysis Paper",
    description:
      "Synthesize statistical findings from multiple studies on a specific topic.",
    category: "Research",
    subcategory: "Academic",
    icon: "📈",
    gradient: "from-blue-600 to-sky-600",
    bgGradient: "from-blue-900/20 to-sky-900/20",
  },
  {
    id: 108,
    title: "Theoretical Framework",
    description:
      "Develop a conceptual structure to explain phenomena and guide research.",
    category: "Research",
    subcategory: "Academic",
    icon: "🧩",
    gradient: "from-indigo-600 to-violet-600",
    bgGradient: "from-indigo-900/20 to-violet-900/20",
  },
  {
    id: 109,
    title: "Ethnographic Research",
    description:
      "Explore cultural phenomena through immersive observation and analysis.",
    category: "Research",
    subcategory: "Academic",
    icon: "👥",
    gradient: "from-rose-600 to-pink-600",
    bgGradient: "from-rose-900/20 to-pink-900/20",
  },
  {
    id: 110,
    title: "Archaeological Report",
    description:
      "Document archaeological findings with contextual analysis and significance.",
    category: "Research",
    subcategory: "Academic",
    icon: "🏺",
    gradient: "from-amber-600 to-yellow-600",
    bgGradient: "from-amber-900/20 to-yellow-900/20",
  },

  // Scientific Research
  {
    id: 111,
    title: "Biology Research Paper",
    description:
      "Investigate biological systems, processes, or organisms with scientific rigor.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🧬",
    gradient: "from-green-600 to-emerald-600",
    bgGradient: "from-green-900/20 to-emerald-900/20",
  },
  {
    id: 112,
    title: "Physics Experiment Analysis",
    description:
      "Examine physical phenomena through experimental data and theoretical models.",
    category: "Research",
    subcategory: "Scientific",
    icon: "⚛️",
    gradient: "from-blue-600 to-indigo-600",
    bgGradient: "from-blue-900/20 to-indigo-900/20",
  },
  {
    id: 113,
    title: "Chemistry Investigation",
    description:
      "Document chemical reactions, properties, and implications with precision.",
    category: "Research",
    subcategory: "Scientific",
    icon: "⚗️",
    gradient: "from-purple-600 to-violet-600",
    bgGradient: "from-purple-900/20 to-violet-900/20",
  },
  {
    id: 114,
    title: "Environmental Impact Study",
    description:
      "Assess ecological effects of human activities with data-driven analysis.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🌍",
    gradient: "from-teal-600 to-green-600",
    bgGradient: "from-teal-900/20 to-green-900/20",
  },
  {
    id: 115,
    title: "Astronomical Observation",
    description:
      "Document celestial phenomena with mathematical models and visual data.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🔭",
    gradient: "from-slate-600 to-gray-600",
    bgGradient: "from-slate-900/20 to-gray-900/20",
  },
  {
    id: 116,
    title: "Medical Research Report",
    description:
      "Investigate health conditions, treatments, or medical technologies.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🩺",
    gradient: "from-sky-600 to-blue-600",
    bgGradient: "from-sky-900/20 to-blue-900/20",
  },
  {
    id: 117,
    title: "Geological Survey",
    description:
      "Analyze earth materials, formations, and processes with technical detail.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🪨",
    gradient: "from-stone-600 to-amber-600",
    bgGradient: "from-stone-900/20 to-amber-900/20",
  },
  {
    id: 118,
    title: "Neuroscience Study",
    description:
      "Explore brain function, neural processes, and cognitive mechanisms.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🧠",
    gradient: "from-violet-600 to-purple-600",
    bgGradient: "from-violet-900/20 to-purple-900/20",
  },
  {
    id: 119,
    title: "Climatology Research",
    description:
      "Analyze climate patterns, changes, and impacts with data visualization.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🌡️",
    gradient: "from-sky-600 to-cyan-600",
    bgGradient: "from-sky-900/20 to-cyan-900/20",
  },
  {
    id: 120,
    title: "Agricultural Research",
    description:
      "Investigate farming methods, crop yields, and sustainable practices.",
    category: "Research",
    subcategory: "Scientific",
    icon: "🌾",
    gradient: "from-lime-600 to-green-600",
    bgGradient: "from-lime-900/20 to-green-900/20",
  },

  // Social Sciences Research
  {
    id: 121,
    title: "Sociological Analysis",
    description:
      "Examine social structures, behaviors, and group dynamics with theory and data.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "👪",
    gradient: "from-indigo-600 to-blue-600",
    bgGradient: "from-indigo-900/20 to-blue-900/20",
  },
  {
    id: 122,
    title: "Psychological Study",
    description:
      "Investigate mental processes, behaviors, and emotional patterns.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🧠",
    gradient: "from-rose-600 to-pink-600",
    bgGradient: "from-rose-900/20 to-pink-900/20",
  },
  {
    id: 123,
    title: "Economic Analysis",
    description:
      "Analyze market trends, economic policies, and financial systems.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "📉",
    gradient: "from-emerald-600 to-green-600",
    bgGradient: "from-emerald-900/20 to-green-900/20",
  },
  {
    id: 124,
    title: "Political Science Research",
    description:
      "Examine governance systems, political behaviors, and policy outcomes.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🏛️",
    gradient: "from-blue-600 to-indigo-600",
    bgGradient: "from-blue-900/20 to-indigo-900/20",
  },
  {
    id: 125,
    title: "Anthropological Study",
    description:
      "Investigate human cultures, societies, and evolutionary development.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🏺",
    gradient: "from-amber-600 to-orange-600",
    bgGradient: "from-amber-900/20 to-orange-900/20",
  },
  {
    id: 126,
    title: "Linguistic Analysis",
    description:
      "Explore language structures, usage patterns, and communication systems.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🗣️",
    gradient: "from-violet-600 to-purple-600",
    bgGradient: "from-violet-900/20 to-purple-900/20",
  },
  {
    id: 127,
    title: "Educational Research",
    description:
      "Examine learning methods, educational outcomes, and teaching approaches.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🎓",
    gradient: "from-sky-600 to-cyan-600",
    bgGradient: "from-sky-900/20 to-cyan-900/20",
  },
  {
    id: 128,
    title: "Urban Planning Study",
    description:
      "Analyze city development, spatial organization, and community needs.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "🏙️",
    gradient: "from-slate-600 to-gray-600",
    bgGradient: "from-slate-900/20 to-gray-900/20",
  },
  {
    id: 129,
    title: "Media Studies Analysis",
    description:
      "Investigate communications media, content patterns, and social impacts.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "📱",
    gradient: "from-fuchsia-600 to-pink-600",
    bgGradient: "from-fuchsia-900/20 to-pink-900/20",
  },
  {
    id: 130,
    title: "Gender Studies Research",
    description:
      "Examine gender roles, identities, and related social structures.",
    category: "Research",
    subcategory: "Social Sciences",
    icon: "⚧️",
    gradient: "from-purple-600 to-violet-600",
    bgGradient: "from-purple-900/20 to-violet-900/20",
  },

  // Business & Technical Research
  {
    id: 131,
    title: "Market Research Report",
    description:
      "Analyze industry trends, consumer behaviors, and competitive landscapes.",
    category: "Research",
    subcategory: "Business",
    icon: "📊",
    gradient: "from-blue-600 to-sky-600",
    bgGradient: "from-blue-900/20 to-sky-900/20",
  },
  {
    id: 132,
    title: "Business Case Study",
    description:
      "Examine organizational strategies, challenges, and outcomes in detail.",
    category: "Research",
    subcategory: "Business",
    icon: "💼",
    gradient: "from-indigo-600 to-blue-600",
    bgGradient: "from-indigo-900/20 to-blue-900/20",
  },
  {
    id: 133,
    title: "Technical Feasibility Study",
    description:
      "Assess the viability of technical projects with resource analysis.",
    category: "Research",
    subcategory: "Business",
    icon: "🔧",
    gradient: "from-slate-600 to-gray-600",
    bgGradient: "from-slate-900/20 to-gray-900/20",
  },
  {
    id: 134,
    title: "Product Development Research",
    description:
      "Document the research and testing phase of new product creation.",
    category: "Research",
    subcategory: "Business",
    icon: "🛠️",
    gradient: "from-amber-600 to-orange-600",
    bgGradient: "from-amber-900/20 to-orange-900/20",
  },
  {
    id: 135,
    title: "Investment Analysis",
    description:
      "Evaluate financial opportunities with risk assessment and projections.",
    category: "Research",
    subcategory: "Business",
    icon: "💰",
    gradient: "from-emerald-600 to-green-600",
    bgGradient: "from-emerald-900/20 to-green-900/20",
  },
  {
    id: 136,
    title: "Supply Chain Analysis",
    description:
      "Investigate logistics systems, efficiencies, and optimization strategies.",
    category: "Research",
    subcategory: "Business",
    icon: "🔗",
    gradient: "from-cyan-600 to-teal-600",
    bgGradient: "from-cyan-900/20 to-teal-900/20",
  },
  {
    id: 137,
    title: "Technology Trend Analysis",
    description:
      "Examine emerging tech innovations and their potential impacts.",
    category: "Research",
    subcategory: "Business",
    icon: "💻",
    gradient: "from-violet-600 to-purple-600",
    bgGradient: "from-violet-900/20 to-purple-900/20",
  },
  {
    id: 1,
    title: "Science Fiction Novel",
    description:
      "Generate a futuristic sci-fi novel with complex characters and technology.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🚀",
    gradient: "from-purple-600 to-blue-600",
    bgGradient: "from-purple-900/20 to-blue-900/20",
  },
  {
    id: 2,
    title: "Fantasy Adventure",
    description:
      "Create a magical fantasy world with heroes, creatures, and epic quests.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🏰",
    gradient: "from-green-600 to-teal-600",
    bgGradient: "from-green-900/20 to-teal-900/20",
  },
  {
    id: 3,
    title: "Mystery Thriller",
    description:
      "Craft a suspenseful mystery with twists, clues, and compelling characters.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🔍",
    gradient: "from-blue-600 to-indigo-600",
    bgGradient: "from-blue-900/20 to-indigo-900/20",
  },
  {
    id: 4,
    title: "Historical Fiction",
    description:
      "Blend historical events with fictional characters and engaging narratives.",
    category: "Book",
    subcategory: "Fiction",
    icon: "📜",
    gradient: "from-amber-600 to-orange-600",
    bgGradient: "from-amber-900/20 to-orange-900/20",
  },
  {
    id: 5,
    title: "Dystopian Future",
    description:
      "Explore a dark future society with social commentary and survival themes.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🏙️",
    gradient: "from-slate-600 to-gray-600",
    bgGradient: "from-slate-900/20 to-gray-900/20",
  },
  {
    id: 6,
    title: "Romance Novel",
    description:
      "Develop a heartwarming love story with compelling relationship dynamics.",
    category: "Book",
    subcategory: "Fiction",
    icon: "💖",
    gradient: "from-pink-600 to-rose-600",
    bgGradient: "from-pink-900/20 to-rose-900/20",
  },
  {
    id: 7,
    title: "Horror Novel",
    description:
      "Create a terrifying tale with suspense, supernatural elements, and dread.",
    category: "Book",
    subcategory: "Fiction",
    icon: "👻",
    gradient: "from-red-600 to-rose-600",
    bgGradient: "from-red-900/20 to-rose-900/20",
  },
  {
    id: 8,
    title: "Adventure Epic",
    description:
      "Craft an exciting journey with exploration, danger, and character growth.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🧭",
    gradient: "from-amber-600 to-yellow-600",
    bgGradient: "from-amber-900/20 to-yellow-900/20",
  },
  {
    id: 9,
    title: "Young Adult Fiction",
    description:
      "Write a coming-of-age story with themes relevant to teenage experiences.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🧑‍🤝‍🧑",
    gradient: "from-cyan-600 to-blue-600",
    bgGradient: "from-cyan-900/20 to-blue-900/20",
  },
  {
    id: 10,
    title: "Urban Fantasy",
    description:
      "Blend magical elements with modern city settings and contemporary issues.",
    category: "Book",
    subcategory: "Fiction",
    icon: "🌆",
    gradient: "from-violet-600 to-purple-600",
    bgGradient: "from-violet-900/20 to-purple-900/20",
  },

  // Books - Non-Fiction
  {
    id: 11,
    title: "Self-Help Guide",
    description:
      "Create a practical guide for personal development and positive change.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "🧠",
    gradient: "from-green-600 to-emerald-600",
    bgGradient: "from-green-900/20 to-emerald-900/20",
  },
  {
    id: 12,
    title: "Business Strategy",
    description:
      "Develop insights on leadership, management, and business growth.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "📊",
    gradient: "from-blue-600 to-sky-600",
    bgGradient: "from-blue-900/20 to-sky-900/20",
  },
  {
    id: 13,
    title: "Personal Memoir",
    description:
      "Tell a compelling life story with meaningful experiences and lessons.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "📝",
    gradient: "from-orange-600 to-amber-600",
    bgGradient: "from-orange-900/20 to-amber-900/20",
  },
  {
    id: 14,
    title: "Popular Science",
    description:
      "Explain scientific concepts in an engaging, accessible manner.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "🔬",
    gradient: "from-cyan-600 to-teal-600",
    bgGradient: "from-cyan-900/20 to-teal-900/20",
  },
  {
    id: 15,
    title: "Historical Biography",
    description:
      "Explore the life and impact of a significant historical figure.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "👑",
    gradient: "from-amber-600 to-yellow-600",
    bgGradient: "from-amber-900/20 to-yellow-900/20",
  },
  {
    id: 16,
    title: "Philosophy Exploration",
    description:
      "Discuss philosophical concepts and their relevance to modern life.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "💭",
    gradient: "from-indigo-600 to-purple-600",
    bgGradient: "from-indigo-900/20 to-purple-900/20",
  },
  {
    id: 17,
    title: "Travel Guide",
    description:
      "Create an informative guide for destinations with cultural insights.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "✈️",
    gradient: "from-blue-600 to-cyan-600",
    bgGradient: "from-blue-900/20 to-cyan-900/20",
  },
  {
    id: 18,
    title: "Cooking & Recipes",
    description:
      "Compile culinary techniques and recipes with cultural context.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "🍳",
    gradient: "from-red-600 to-orange-600",
    bgGradient: "from-red-900/20 to-orange-900/20",
  },
  {
    id: 19,
    title: "Health & Wellness",
    description:
      "Provide guidance on physical and mental wellbeing with practical advice.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "🧘",
    gradient: "from-green-600 to-lime-600",
    bgGradient: "from-green-900/20 to-lime-900/20",
  },
  {
    id: 20,
    title: "Financial Literacy",
    description:
      "Explain personal finance concepts with actionable strategies.",
    category: "Book",
    subcategory: "Non-Fiction",
    icon: "💰",
    gradient: "from-emerald-600 to-green-600",
    bgGradient: "from-emerald-900/20 to-green-900/20",
  },

  // Stories - Short Fiction
  {
    id: 21,
    title: "Short Horror Story",
    description:
      "Craft a gripping horror tale with suspense and unexpected twists.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🖤",
    gradient: "from-red-600 to-rose-600",
    bgGradient: "from-red-900/20 to-rose-900/20",
  },
  {
    id: 22,
    title: "Flash Fiction",
    description:
      "Create an impactful story under 1000 words with a powerful message.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "⚡",
    gradient: "from-amber-600 to-yellow-600",
    bgGradient: "from-amber-900/20 to-yellow-900/20",
  },
  {
    id: 23,
    title: "Sci-Fi Short Story",
    description:
      "Explore futuristic concepts in a concise, thought-provoking format.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🛸",
    gradient: "from-violet-600 to-indigo-600",
    bgGradient: "from-violet-900/20 to-indigo-900/20",
  },
  {
    id: 24,
    title: "Romance Short Story",
    description: "Develop a heartwarming romantic tale with emotional depth.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "❤️",
    gradient: "from-pink-600 to-rose-600",
    bgGradient: "from-pink-900/20 to-rose-900/20",
  },
  {
    id: 25,
    title: "Mystery Short Story",
    description:
      "Create an intriguing mystery with clever clues and a satisfying resolution.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🕵️",
    gradient: "from-blue-600 to-indigo-600",
    bgGradient: "from-blue-900/20 to-indigo-900/20",
  },
  {
    id: 26,
    title: "Historical Fiction Tale",
    description:
      "Craft a story set in the past with historical accuracy and engaging characters.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🏛️",
    gradient: "from-amber-600 to-orange-600",
    bgGradient: "from-amber-900/20 to-orange-900/20",
  },
  {
    id: 27,
    title: "Fable or Allegory",
    description:
      "Create a story with moral lessons using symbolism and metaphor.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🦊",
    gradient: "from-green-600 to-emerald-600",
    bgGradient: "from-green-900/20 to-emerald-900/20",
  },
  {
    id: 28,
    title: "Magical Realism",
    description:
      "Blend realistic settings with subtle magical elements for a unique story.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "✨",
    gradient: "from-purple-600 to-fuchsia-600",
    bgGradient: "from-purple-900/20 to-fuchsia-900/20",
  },
  {
    id: 29,
    title: "Adventure Short Story",
    description:
      "Create an exciting tale of exploration and discovery in a condensed format.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🗺️",
    gradient: "from-yellow-600 to-amber-600",
    bgGradient: "from-yellow-900/20 to-amber-900/20",
  },
  {
    id: 30,
    title: "Dystopian Short Story",
    description:
      "Explore societal issues through a brief but impactful dystopian narrative.",
    category: "Story",
    subcategory: "Short Fiction",
    icon: "🏚️",
    gradient: "from-slate-600 to-gray-600",
    bgGradient: "from-slate-900/20 to-gray-900/20",
  },

  // Stories - Non-Fiction
  {
    id: 31,
    title: "Personal Essay",
    description:
      "Craft a reflective piece exploring personal experiences and insights.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "📓",
    gradient: "from-blue-600 to-sky-600",
    bgGradient: "from-blue-900/20 to-sky-900/20",
  },
  {
    id: 32,
    title: "Travel Narrative",
    description:
      "Share an engaging account of travel experiences and cultural encounters.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "🧳",
    gradient: "from-cyan-600 to-blue-600",
    bgGradient: "from-cyan-900/20 to-blue-900/20",
  },
  {
    id: 33,
    title: "Nature Observation",
    description:
      "Describe natural phenomena with scientific accuracy and artistic language.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "🌿",
    gradient: "from-green-600 to-lime-600",
    bgGradient: "from-green-900/20 to-lime-900/20",
  },
  {
    id: 34,
    title: "Historical Event Narrative",
    description:
      "Recount a historical event with contextual details and human perspectives.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "📜",
    gradient: "from-orange-600 to-amber-600",
    bgGradient: "from-orange-900/20 to-amber-900/20",
  },
  {
    id: 35,
    title: "Profile Story",
    description:
      "Create an in-depth portrait of a person with insights into their life.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "👤",
    gradient: "from-indigo-600 to-violet-600",
    bgGradient: "from-indigo-900/20 to-violet-900/20",
  },
  {
    id: 36,
    title: "Sports Narrative",
    description:
      "Tell the story of a sporting event or athlete with drama and insight.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "🏆",
    gradient: "from-red-600 to-orange-600",
    bgGradient: "from-red-900/20 to-orange-900/20",
  },
  {
    id: 37,
    title: "Medical Experience",
    description:
      "Share a healthcare story with emotional depth and medical accuracy.",
    category: "Story",
    subcategory: "Non-Fiction",
    icon: "🩺",
    gradient: "from-blue-600 to-cyan-600",
  },
];
